App/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :movies do
  	collection do 
  		get 'search'
  	end
  	resources :reviews, except: [:show, :index]
  end

  
  root 'movies#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

App/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

App/app/models/movie.rb
 class Movie < ApplicationRecord
	searchkick
	belongs_to :user
	has_many :reviews

	has_attached_file :image, styles: { medium: "300x500>" }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

	has_attached_file :video, styles: { medium: { geometry: "640x480", format: 'mp4'},
		thumb: { geometry: "100x50", format: 'jpg', time: 10}
	}, processor: [:transcoder]
	validates_attachment_content_type :video, content_type: /\Avideo\/.*\z/
end

App/app/models/review.rb
class Review < ApplicationRecord
	belongs_to :user
	belongs_to :movie
end

App/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :movies
  has_many :reviews, dependent: :destroy
end

App/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

App/app/controllers/as.rb
class LayoutsController < ApplicationController
	def _header
    	@user = User.first
	end
end

App/app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy, :del]
  before_action :authenticate_user!, except: [:index, :show, :del]

  # GET /movies
  # GET /movies.json
  def search
    if params[:search].present?
      @movies = Movie.search(params[:search])
    else
      @movies = Movie.all
    end
  end



  def index
    @movies = Movie.all
    @user = current_user
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    @reviews = Review.where(movie_id: @movie.id).order("created_at DESC")
    @user = current_user
    if @reviews.blank?
      @avg_review = 0
    else
      @avg_review = @reviews.average(:rating).round(2)
    end
  end

  # GET /movies/new
  def new
    @movie = current_user.movies.build
  end

  # GET /movies/1/edit
  def edit
  end

  def del
    @movie = current_user.movies.build
  end
  # POST /movies
  # POST /movies.json
  def create
    @movie = current_user.movies.build(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :description, :movie_length, :director, :cast, :rating, :image, :video)
    end
end

App/app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

App/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :set_movie
  before_action :authenticate_user!


  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit

    
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.movie_id = @movie.id
    respond_to do |format|
      if @review.save
        format.html { redirect_to @movie, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @movie, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review = Review.last
    @review.destroy
    respond_to do |format|
      format.html { redirect_to @movies, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    def set_movie
      @movie = Movie.find(params[:movie_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:rating, :comment, :name)
    end
end

App/app/helpers/application_helper.rb
module ApplicationHelper
end

App/app/helpers/layouts_helper.rb
module LayoutsHelper
end

App/app/helpers/movies_helper.rb
module MoviesHelper
end

App/app/helpers/reviews_helper.rb
module ReviewsHelper
end

App/app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation" style="background-color: #3d4147;">
	<div class="container" >
		<div class="navbar-header" >
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= link_to "Movie Reviews", root_path, class: "navbar-brand",style: "color: white", onMouseOver: "this.style.color='blue'", onMouseOut: "this.style.color='white'" %>
		</div>

		<div class = "collapse navbar-collapse" id = "bs-example-navbar-collapse-1" >
			<ul class="nav navbar-nav">
				<% if user_signed_in? %>
					<li><%= link_to "Update Account", edit_user_registration_path, class: "active", style: "color: white",  onMouseOver: "this.style.color='blue'", onMouseOut: "this.style.color='white'" %></li>
					<li><%= link_to "Log Out", destroy_user_session_path, method: :delete,  class: "active", style: "color: white",  onMouseOver: "this.style.color='blue'", onMouseOut: "this.style.color='white'" %></li>
				<% else %>
					<li><%= link_to "Sign Up", new_user_registration_path, class: "active", onMouseOver: "this.style.color='blue'", onMouseOut: "this.style.color='white'" , style: "color: white" %></li>
					<li><%= link_to "Sign In", new_user_session_path, class: "active", style: "color: white", onMouseOver: "this.style.color='blue'", onMouseOut: "this.style.color='white'" %></li>
				<% end %>
			</ul>
			<%= form_tag search_movies_path, method: :get, class: "navbar-form navbar-right", role: "search" do %>
			<p>
				<%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search Movies" %>
				<%= submit_tag "Search", name: nil, class: "btn btn-info" %>
			</p>

			<% end %>
		</div>
	</div>
</nav>

App/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lays</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |name,msg| %>
        <%= content_tag(:div, msg, class: "alert alert-info") %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>
 <%= yield :javascript_includes %>

App/app/views/movies/_form.html.erb
<%= form_with(model: movie, local: true, html: { multipart: true }) do |form| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div  style="background-color: #030b33; color: white; padding-left: 5%; width: 40%; margin-left: 30%; border-radius: 8px;">
    <br>
  <div class="field">
    <%= form.label :title %><br>
    <%= form.text_field :title , class: "abc" %>
  </div>

  <div class="field">
    <%= form.label :description %><br>
    <%= form.text_area :description, class: "abc" %>
  </div>

  <div class="field">
    <%= form.label :movie_length %><br>
    <%= form.text_field :movie_length, class: "abc" %>
  </div>

  <div class="field">
    <%= form.label :director %><br>
    <%= form.text_field :director, class: "abc" %>
  </div>

  <div class="field">
    <%= form.label :cast %><br>
    <%= form.text_area :cast, class: "abc" %>
  </div>

  <div class="field">
    <%= form.label :rating %><br>
    <%= form.text_field :rating, class: "abc" %>
  </div>

  <div class="field"><br>
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

   <div class="field"><br>
    <%= form.label :video %>
    <%= form.file_field :video, class: "form-control" %>
  </div>

  <div class="actions"><br>
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %><br>
<br>
</div>
<br>
<div style="margin-left: 48%;">
<%= link_to 'Back', movies_path, class: "btn btn-success" %><div><br>
<br><br>

App/app/views/movies/edit.html.erb
<div style="color: white; padding-left: 5%; width: 40%; margin-left: 30%; border-radius: 8px;"><br>
	<h1 style="margin-left: 20%">Editing Movie</h1><br>
</div>
<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

App/app/views/movies/index.html.erb
<% if !user_signed_in? %>
<div class="jumbotron">
  <h1><b>Movie Critics<b></h1>
  <p><i>Whether a movie is a rotten tomato or a brilliant work of art, if people are watching it, it's worth critiquing. A decent movie review should entertain, persuade and inform, providing an original opinion without giving away too much of the plot. A great movie review can be a work of art in its own right. Read on to learn how to analyze a movie, come up with an interesting thesis and write a review as entertaining as your source material.<i></p>
  <p><%= link_to "Sign Up To Write A Review", new_user_registration_path, class:"btn btn-primary btn-lg" %></p>
</div>
<% end %>
<div style="margin-left: 80%;">
  <% if user_signed_in? %>
    <% if @user.email == "broyogesh88@gmail.com" %>
     <%= link_to "Add New Movie", new_movie_path, class: "btn btn-info",style: "color: white", onMouseOver: "this.style.color='blue'", onMouseOut: "this.style.color='white'" %>
  <% end %>
  <% end %>
  </div>
  <br>
<div class="row">
  <% @movies.each do |movie| %> 
    <div class="col-sm-6 col-md-3">  
      <div class="thumbnail">
        <%= link_to (image_tag movie.image.url(:medium, :size => "300x500"),class: 'image' ), movie %>
      </div>
    </div>

  <% end %>
</div> 

App/app/views/movies/new.html.erb
<div style="color: white; padding-left: 5%; width: 40%; margin-left: 30%; border-radius: 8px;"><br>
	<h1 style="margin-left: 20%">New Movie</h1><br>
</div>

<%= render 'form', movie: @movie %>

App/app/views/movies/search.html.erb
<div class="row">
  <% @movies.each do |movie| %> 
    <div class="col-sm-6 col-md-3">  
      <div class="thumbnail">
        <%= link_to (image_tag movie.image.url(:medium),class: 'image'), movie %>

      </div>
    </div>

  <% end %>
</div> 

App/app/views/movies/show.html.erb
<% content_for :javascript_includes do %>
  <%= javascript_include_tag 'jquery.raty.js' %>
<% end %>

<p id="notice"><%= notice %></p>
<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-md-4">
        <%= image_tag @movie.image.url(:medium) %>
        <div></div>
       <div class="star-rating" data-score= <%= @avg_review %> ></div>
       <p><%= @avg_review %>/10</p> 
        <em><%= "#{@reviews.length} reviews" %>
        <div class="table-responsive">
          <table class="table">
            <tbody>
              <tr>
                <td><strong>Title:</strong></td>
                <td><%= @movie.title %></td>
              </tr>
              <tr>
                <td><strong>Description:</strong></td>
                <td><%= @movie.description %></td>
              </tr>
              <tr>
                <td><strong>Movie Length:</strong></td>
                <td><%= @movie.movie_length %></td>
              </tr>
              <tr>
                <td><strong>Director:</strong></td>
                <td><%= @movie.director %></td>
              </tr>
              <tr>
                <td><strong>Cast:</strong></td>
                <td><%= @movie.cast %></td>
              </tr>
              <tr>
               <td><strong>IMDB Rating:</strong></td>
                <td><%= @movie.rating %></td> -->
              </tr>
            </tbody>
          </table>
        </div>
      </div>

    <div class="col-md-7 col-md-offset">
        <% if user_signed_in? %>
           <% if @user.email == "broyogesh88@gmail.com" %>
           <div style="margin-left: 30%;">
            <%= link_to 'Click here to Edit Movie Details', edit_movie_path(@movie), class: "btn btn-danger" %>
            </div><br>
          <% end %>
        <% end %>
        <h1 class="review_title"><%= @movie.title %></h1>
        <h4>About this Movie</h4>
        <div style="background-color: grey; border-radius: 8px; padding-left: 5px;" >
            <%= @movie.description %>
        </div><br>
        <h4>Trailer:</h4>
        <%= video_tag @movie.video.url, :size => "620x440", :controls => true %><br><br>
        <% if @reviews.blank? %>
                <h3>No review just yet, be the first person to review it.</h3>
                <%= link_to "Write Review", new_movie_review_path(@movie), class: "btn btn-danger" %>
        <% else %>

            <% @reviews.each do |review| %>
            <div class="reviews">
                <p><%= review.name %>:</p>
               <div class="star-rating" data-score= <%= review.rating %> ></div>
                <p><%= review.comment %></p>
                <% if review.user_id == @user.id %>
              <% end %>
            </div>
          <% end %>
          <br>
          <%= link_to "Write a Review", new_movie_review_path(@movie), class: "btn btn-danger" %>
          <% end %>
    </div>

  </div>
  <br><br>

  <div style="margin-left: 45%; ">
        <%= link_to 'Back', movies_path , class: "btn btn-success"%>
  </div>
<br>
</div><br><br>

<script>
    $('.star-rating').raty({
      path: '/assets/',
      readOnly: true,
      score: function() {
            return $(this).attr('data-score');
    }
  });
</script>

App/app/views/reviews/_form.html.erb
<%= simple_form_for([@movie, @review]) do |form| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div  style="background-color: #030b33; color: white; padding-left: 5%; width: 40%; margin-left: 30%; border-radius: 8px;">
  <br>
  <h1>New Review</h1>
<br>

  <div class="field">
    <%= form.label :name %><br>
    <%= form.text_field :name, class: "abc" %>
  </div>
  <br>
    <%= form.label :rating %>
    <div class="field">
     <div id="star-rating">
    </div>
    <br>
  </div>
  <div class="field">
    <%= form.label :comment %><br>
    <%= form.text_area :comment, class: "abc" %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
    <% end %>
    <br><br>
    <%= link_to 'Back', movie_path(@movie), style: "margin-left: 35%", class: "btn btn-success" %>
    <br><br>
</div>


<script>
  $('#star-rating').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
  });
</script>

App/app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review  %>

<%= link_to 'Back', movie_path(@movie) %>

App/app/views/reviews/new.html.erb
<%= render 'form' %>